travis:
  secure:
    BINSTAR_TOKEN: KOO0zpKP1gtcxA3y8JByTMPlSTamjhsqHT/oLtpXpXps+GiNgob4XXKrr9iDNUt74Tyq51I+gD2tebqCYRunaseBKT3/MwgxhKMwEypYgpJito274Z9cEWpp2u5YowOSLsnApLlGpWK0bbQH2vaUdCI6ahDMafAU1E2uCzqJHvXSLS434yERCR+H3MymSFOpI6M9FXqg4erW2dRPudBbZkb2N972gEQIQXFYDujcEJxgQlirlIY1XHcE52gqolBe8dWJ4dsEiCsWffoMxT3tThZ0TG4i5eZw1KZ0PK7ebJUYMQhnygbetogLmWWsoEA4L3tdDGR0++rSUE/eGA1YAmAEaE9MkXAxpJWliVUYOonRCuzSqB4p26uCwdCH8I64ZO7MxOVxZuqOepweh9FD1pySA8XYZrgZNVwRa1mJXC4FcO4zJlAmlhxivohd9ezO/fzSFGxwsNqTOu9/slsjv0vO/LJzepgvXmr92WR5IRRUndvxn3AbqZbIZDozAI2gf2lRbAlCQBQbRdheyzjfOkbdJRIrSlW9JjBpi6grStuAax+zEQVuYCoYKuR8Cs1TlrMRQryAPMc6qSPBvM21fDHbl8xyd1TXD0sUU3pNEmL0uZDw4IWYZ43EJ6o27Mp88lKkgQLkADb2WXTDdswqGKY0VVc6ARiWUoPtz5VuUTA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
