travis:
  secure:
    BINSTAR_TOKEN: ipL6BIvWHpbOVelgxvEu7ipHSWqZnuhhn2MiOvIYk1KEwFV5ZNzVpStttPngD77UdHR2kVARWVb0Qb+DJQ7ZbZpCYYKqo7obtid4/xkIhZTwzofl0GInwxs1Y7+vnBZuYyzK3jh8AQHj6Wrp8h9AIs6m1ma5XMlQM+yW3H29PgD00xPRMtfm6VjlNbj3fNaB/ZJX+1uDShRsjLs451NMdMKQ++tr5d1Tb+vIKCsYJcWUNQU8xElSYf4Upu9qta47WR6XhZKBqyvAjbgmhLC0bcXg6Y1ZVg04xwFdVgSzkFHe2ykUDbDWXhYfBl+cLrEpv704ITFVJBsh5Lderz5B/mGajwGp5AbtqL1gRwoFLxy7R2q1ZhrTUsdnK46EzZn3zx5a3mM+ZAmndavb3TKsC6tIU142morapG+hMjwwZYb0Ed/HJ9DowEcUMXjn0YPfxBwNmfNQh+yGwgMkCaSSoNQjr1XcWqHsGVDJTZh7fJbRzbn1DJcNEo93bs3Va/BNO/WAcHoX+UVDXWm3G4PXQUxb+HMZ5Bz7kJOkQlFHADm2p9o13o1oKRjMnfSYQEWt3uu+K7tl2OI2BuOkK6iZDrmGt+vmEPrDSJoJYRJousE1jJP6gZiMjuYZAcs2Kl2btLew75KieNdWK6mHrRSf9h/JAxDA9XKmkK+CzsppjcQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
